AWSTemplateFormatVersion: 2010-09-09
Description: Housekeeping for Ophan
Parameters:
  App:
    Description: Application name
    Type: String
    Default: housekeeper
Resources:
  ExecutionRole:
    Type: AWS::IAM::Role
    DependsOn: PermanentEmailBounceTopic
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action: sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: logging
          PolicyDocument:
            Statement:
              Effect: Allow
              Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource: arn:aws:logs:*:*:*
        - PolicyName: housekeeping-actions
          PolicyDocument:
            Statement:
            - Effect: Allow
              Action:
                - "dynamodb:Query"
                - "dynamodb:DeleteItem"
              Resource:
                - "arn:aws:dynamodb:*:021353022223:table/ophan-alerts"
                - "arn:aws:dynamodb:*:021353022223:table/DEV-ophan-alerts"
            - Effect: Allow
              Action:
                - sns:Publish
              Resource: !Ref PermanentEmailBounceTopic
  BounceSNSTopic:
    Type: "AWS::SNS::Topic"
    DependsOn: Lambda
    Properties:
      DisplayName: SNS topic alerted when AWS SES emails bounce (eg from Ophan Dashboard alerts, or Airflow)
      Subscription:
        - Protocol: lambda
          Endpoint: !GetAtt Lambda.Arn
      TopicName: ses-email-bounce-notifications-for-housekeeper

  PermanentEmailBounceTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: Threat to email-sending ability of Ophan's AWS account

  Lambda:
    Type: AWS::Lambda::Function
    DependsOn: PermanentEmailBounceTopic
    Properties:
      Code:
        S3Bucket: ophan-dist
        S3Key: ophan/PROD/housekeeper/housekeeper.jar
      Description: Housekeeping for Ophan
      Environment:
        Variables:
          PermanentEmailBounceTopicArn: !Ref PermanentEmailBounceTopic
      Handler: housekeeper.Lambda::handler
      MemorySize: 512
      Role: !GetAtt ExecutionRole.Arn
      Runtime: java11
      Timeout: 30
  LambdaInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      Principal: sns.amazonaws.com
      SourceArn:
        Ref: BounceSNSTopic
      FunctionName: !GetAtt Lambda.Arn
