AWSTemplateFormatVersion: 2010-09-09
Description: A lambda that uses the GeoIPUpdater to download an updated dump of GeoIP data and place it in a specified S3 bucket
Parameters:
  App:
    Description: Application name
    Type: String
    Default: geoip-updater
Resources:
  ExecutionRole:
    Type: AWS::IAM::Role
    DependsOn: PermanentEmailBounceTopic
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action: sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: logging
          PolicyDocument:
            Statement:
              Effect: Allow
              Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource: arn:aws:logs:*:*:*

  Lambda:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: ophan-dist
        S3Key: ophan/PROD/housekeeper/geoip-updater.jar
      Description: A lambda that uses the GeoIPUpdater to download an updated dump of GeoIP data and place it in a specified S3 bucket
      Handler: com.gu.ophan.housekeeper.Lambda::handler
      MemorySize: 512
      Role: !GetAtt ExecutionRole.Arn
      Runtime: java8
      Timeout: 30
  LambdaInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      Principal: sns.amazonaws.com
      SourceArn:
        Ref: BounceSNSTopic
      FunctionName: !GetAtt Lambda.Arn

  ScheduledEvent:
    Type: AWS::Events::Rule
    Properties:
      Description: Run every minute (temporarily, for testing)
      ScheduleExpression: rate(1 minute)
      Targets:
        - Id: Lambda
          Arn: !GetAtt Lambda.Arn

  ScheduledEventLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt Lambda.Arn
      Principal: events.amazonaws.com
      SourceArn: !GetAtt ScheduledEvent.Arn